server:
  port: 8084

spring:
  application:
    name: branch-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bms_branch
    username: bms
    password: bms123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    enabled: false          # will turn on once discovery-server works
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info